// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using __CallingConvention = global::System.Runtime.InteropServices.CallingConvention;
using __IntPtr = global::System.IntPtr;

#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required

namespace CyberpunkMp
{
    [SuppressUnmanagedCodeSecurity, UnmanagedFunctionPointer(__CallingConvention.Cdecl)]
    public unsafe delegate void TUpdateCallback(float __0);

    public unsafe partial class ServerAPI : IDisposable
    {
        [StructLayout(LayoutKind.Sequential, Size = 1)]
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity, DllImport("Server.Native", EntryPoint = "_ZN9ServerAPIC2ERKS_", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void cctor(__IntPtr __instance, __IntPtr _0);

            [SuppressUnmanagedCodeSecurity, DllImport("Server.Native", EntryPoint = "_ZN9ServerAPI10InitializeEv", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void Initialize();

            [SuppressUnmanagedCodeSecurity, DllImport("Server.Native", EntryPoint = "_ZN9ServerAPI3RunEv", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void Run();

            [SuppressUnmanagedCodeSecurity, DllImport("Server.Native", EntryPoint = "_ZN9ServerAPI4ExitEv", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void Exit();

            [SuppressUnmanagedCodeSecurity, DllImport("Server.Native", EntryPoint = "_ZN9ServerAPI17SetUpdateCallbackEPFvfE", CallingConvention = __CallingConvention.Cdecl)]
            internal static extern void SetUpdateCallback(__IntPtr callback);
        }

        public __IntPtr __Instance { get; protected set; }

        internal static readonly new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::CyberpunkMp.ServerAPI> NativeToManagedMap =
            new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::CyberpunkMp.ServerAPI>();

        internal static void __RecordNativeToManagedMapping(IntPtr native, global::CyberpunkMp.ServerAPI managed)
        {
            NativeToManagedMap[native] = managed;
        }

        internal static bool __TryGetNativeToManagedMapping(IntPtr native, out global::CyberpunkMp.ServerAPI managed)
        {
    
            return NativeToManagedMap.TryGetValue(native, out managed);
        }

        protected bool __ownsNativeInstance;

        internal static ServerAPI __CreateInstance(__IntPtr native, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            return new ServerAPI(native.ToPointer(), skipVTables);
        }

        internal static ServerAPI __GetOrCreateInstance(__IntPtr native, bool saveInstance = false, bool skipVTables = false)
        {
            if (native == __IntPtr.Zero)
                return null;
            if (__TryGetNativeToManagedMapping(native, out var managed))
                return (ServerAPI)managed;
            var result = __CreateInstance(native, skipVTables);
            if (saveInstance)
                __RecordNativeToManagedMapping(native, result);
            return result;
        }

        internal static ServerAPI __CreateInstance(__Internal native, bool skipVTables = false)
        {
            return new ServerAPI(native, skipVTables);
        }

        private static void* __CopyValue(__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(__Internal));
            *(__Internal*) ret = native;
            return ret.ToPointer();
        }

        private ServerAPI(__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
        }

        protected ServerAPI(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new __IntPtr(native);
        }

        public ServerAPI()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::CyberpunkMp.ServerAPI.__Internal));
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
        }

        public ServerAPI(global::CyberpunkMp.ServerAPI _0)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::CyberpunkMp.ServerAPI.__Internal));
            __ownsNativeInstance = true;
            __RecordNativeToManagedMapping(__Instance, this);
            *((global::CyberpunkMp.ServerAPI.__Internal*) __Instance) = *((global::CyberpunkMp.ServerAPI.__Internal*) _0.__Instance);
        }

        public void Dispose()
        {
            Dispose(disposing: true, callNativeDtor : __ownsNativeInstance );
        }

        partial void DisposePartial(bool disposing);

        internal protected virtual void Dispose(bool disposing, bool callNativeDtor )
        {
            if (__Instance == IntPtr.Zero)
                return;
            NativeToManagedMap.TryRemove(__Instance, out _);
            DisposePartial(disposing);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        public static void Initialize()
        {
            __Internal.Initialize();
        }

        public static void Run()
        {
            __Internal.Run();
        }

        public static void Exit()
        {
            __Internal.Exit();
        }

        public static void SetUpdateCallback(global::CyberpunkMp.TUpdateCallback callback)
        {
            var __arg0 = callback == null ? global::System.IntPtr.Zero : Marshal.GetFunctionPointerForDelegate(callback);
            __Internal.SetUpdateCallback(__arg0);
        }
    }
}
