// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Client.Plugins
{
public static class JobsClient
{
	[ClientRpc(Class = 1545051913836928782, Function = 3896777535515081057)]
	public static void SetActiveJob(ulong playerId, CName job)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteUint64(job.Hash);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 1545051913836928782, 3896777535515081057, data);
		} finally {
			IBuffer.Release(data);
		}
	}

}
}