// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Client.Plugins
{
public static class DeliveryClient
{
	[ClientRpc(Class = 6480547387820577478, Function = 13827181184640131711)]
	public static void ReceiveDelivery(ulong playerId, TweakDBID item, uint count)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteUint32(item.Hash);
		data.WriteUint8(item.Length);
			data.WriteUint32(count);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6480547387820577478, 13827181184640131711, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6480547387820577478, Function = 1176772553204760029)]
	public static void StartDelivery(ulong playerId, Cyberpunk.Rpc.Vector4 location)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			location.Serialize(data);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6480547387820577478, 1176772553204760029, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6480547387820577478, Function = 5091133932620012562)]
	public static void EndDelivery(ulong playerId, bool success, uint reward)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteBool(success);
			data.WriteUint32(reward);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6480547387820577478, 5091133932620012562, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6480547387820577478, Function = 2256954576744231757)]
	public static void LoadItems(ulong playerId, Cyberpunk.Rpc.Plugins.ShopEntry[] items)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			length = (ushort)items.Length;
		data.WriteUint16(length);
		for(uint array_idx = 0; array_idx < length; ++array_idx)
		{
			var _tmp_val = items[array_idx];
			_tmp_val.Serialize(data);
		}
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6480547387820577478, 2256954576744231757, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6480547387820577478, Function = 17511775741481766825)]
	public static void LoadDeliveries(ulong playerId, Cyberpunk.Rpc.Plugins.DeliveryInfo[] deliveries)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			length = (ushort)deliveries.Length;
		data.WriteUint16(length);
		for(uint array_idx = 0; array_idx < length; ++array_idx)
		{
			var _tmp_val = deliveries[array_idx];
			_tmp_val.Serialize(data);
		}
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6480547387820577478, 17511775741481766825, data);
		} finally {
			IBuffer.Release(data);
		}
	}

}
}