// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Client.Plugins
{
public static class TaxiDriverClient
{
	[ClientRpc(Class = 6000116569204576676, Function = 11997344065845730944)]
	public static void StartJob(ulong playerId, Cyberpunk.Rpc.Vector4 pickupLocation)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			pickupLocation.Serialize(data);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6000116569204576676, 11997344065845730944, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6000116569204576676, Function = 9476214292507710553)]
	public static void MountPassenger(ulong playerId, ulong rider_server_id)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteUint64(rider_server_id);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6000116569204576676, 9476214292507710553, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6000116569204576676, Function = 11677952604416569598)]
	public static void StartTrip(ulong playerId, Cyberpunk.Rpc.Vector4 dropoffLocation)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			dropoffLocation.Serialize(data);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6000116569204576676, 11677952604416569598, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6000116569204576676, Function = 12778657023157887943)]
	public static void EndTrip(ulong playerId, bool success, uint reward)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			data.WriteBool(success);
			data.WriteUint32(reward);
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6000116569204576676, 12778657023157887943, data);
		} finally {
			IBuffer.Release(data);
		}
	}

	[ClientRpc(Class = 6000116569204576676, Function = 18408686905027216154)]
	public static void LoadJobs(ulong playerId, Cyberpunk.Rpc.Plugins.TaxiJobInfo[] jobs)
	{
		ushort length = 0;
		var data = IBuffer.Create();
		try{
			length = (ushort)jobs.Length;
		data.WriteUint16(length);
		for(uint array_idx = 0; array_idx < length; ++array_idx)
		{
			var _tmp_val = jobs[array_idx];
			_tmp_val.Serialize(data);
		}
			CyberpunkSdk.Server.RpcManager.Call(playerId, 6000116569204576676, 18408686905027216154, data);
		} finally {
			IBuffer.Release(data);
		}
	}

}
}