rule("csharp")
	set_extensions(".csproj")
	on_build_file(function (target, sourcefile)
		os.runv("dotnet", {"build", sourcefile, "-o", target:targetdir()})
	end)
	on_run(function (target, sourcefile)
		os.runv("dotnet", {"run", sourcefile, "-o", target:targetdir()})
	end)
	on_link(function() end)
rule_end()