// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Server.Plugins
{
public static partial class JobsServer
{
	[ServerRpc(Class = 8330855795318389666, Function = 3664815350867387508)]
	public static void SelectJob(ulong playerId, IBuffer data)
	{
		ushort length = 0;
		var job = new CName(data.ReadUint64());

		SelectJob_Impl(playerId, job);
	}

	public static partial void SelectJob_Impl(ulong playerId, CName job);

	[ServerRpc(Class = 8330855795318389666, Function = 7008247452236044793)]
	public static void QuitJob(ulong playerId, IBuffer data)
	{
		ushort length = 0;

		QuitJob_Impl(playerId);
	}

	public static partial void QuitJob_Impl(ulong playerId);

}
}