// This file is automatically generated

#pragma warning disable CS8618
#pragma warning disable CS0219

using CyberpunkSdk;
using CyberpunkSdk.Types;

using CyberpunkSdk.Systems;

using CyberpunkSdk.Internal;

namespace Cyberpunk.Rpc.Server.Plugins
{
public static partial class DeliveryServer
{
	[ServerRpc(Class = 17171651187470852330, Function = 11656437727327925612)]
	public static void BuyItem(ulong playerId, IBuffer data)
	{
		ushort length = 0;
		var id = new TweakDBID(data.ReadUint32(), data.ReadUint8());
		var count = data.ReadUint32();
		var fees = data.ReadUint32();

		BuyItem_Impl(playerId, id, count, fees);
	}

	public static partial void BuyItem_Impl(ulong playerId, TweakDBID id, uint count, uint fees);

	[ServerRpc(Class = 17171651187470852330, Function = 2887284690878263329)]
	public static void AcceptDelivery(ulong playerId, IBuffer data)
	{
		ushort length = 0;
		var id = data.ReadUint32();

		AcceptDelivery_Impl(playerId, id);
	}

	public static partial void AcceptDelivery_Impl(ulong playerId, uint id);

	[ServerRpc(Class = 17171651187470852330, Function = 12300385085973622707)]
	public static void CancelDelivery(ulong playerId, IBuffer data)
	{
		ushort length = 0;

		CancelDelivery_Impl(playerId);
	}

	public static partial void CancelDelivery_Impl(ulong playerId);

	[ServerRpc(Class = 17171651187470852330, Function = 10241059626252359811)]
	public static void LoadItems(ulong playerId, IBuffer data)
	{
		ushort length = 0;

		LoadItems_Impl(playerId);
	}

	public static partial void LoadItems_Impl(ulong playerId);

	[ServerRpc(Class = 17171651187470852330, Function = 4898030697502022045)]
	public static void LoadDeliveries(ulong playerId, IBuffer data)
	{
		ushort length = 0;

		LoadDeliveries_Impl(playerId);
	}

	public static partial void LoadDeliveries_Impl(ulong playerId);

}
}